In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
df=pd.read_csv('/content/Iris.csv')

In [ ]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.shape

(150, 6)

In [ ]:
df.info

<bound method DataFrame.info of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-seto

In [ ]:
df.describe

<bound method NDFrame.describe of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-se

In [ ]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
#Split the data into features (X) and target (y)
X = df.drop('Species', axis=1)
y = df['Species']

In [ ]:

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Train a logistic regression model
model = LogisticRegression(max_iter=1000)  # Initialize the logistic regression model
model.fit(X_train, y_train)              # Train the model on the training data


LogisticRegression(max_iter=1000)

In [ ]:
#Make predictions on the test set
y_pred = model.predict(X_test)


In [ ]:

#Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

In [ ]:
#Display the accuracy and other evaluation metrics
print(f'Accuracy: {accuracy * 100:.2f}%')
print('\nConfusion Matrix:')
print(confusion)
print('\nClassification Report:')
print(classification_rep)

Accuracy: 100.00%

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [ ]:
from sklearn.tree import DecisionTreeRegressor

In [ ]:
#Split the data into features (X) and target (y)
X = df.drop('Species', axis=1)
y = df['SepalLengthCm']  # Select one of the continuous features as the target variable for regression

In [ ]:
#Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
 #Train a decision tree regressor
model = DecisionTreeRegressor(random_state=42)  # Initialize the decision tree regressor
model.fit(X_train, y_train)                     # Train the model on the training data

DecisionTreeRegressor(random_state=42)

In [ ]:
# Make predictions on the test set
y_pred = model.predict(X_test)

In [ ]:
from sklearn.tree import plot_tree

In [ ]:
# Visualize the decision tree
plt.figure(figsize=(12, 8))
plot_tree(model, filled=True, feature_names=X.columns, rounded=True)
plt.title('Decision Tree Regression')
plt.show()

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

# Calculate R-squared (R2) score
r2 = r2_score(y_test, y_pred)

# Calculate Mean Squared Error (MSE)
mse = mean_squared_error(y_test, y_pred)

# Calculate the mean value of the target variable y_test
mean_value = np.mean(y_test)

# Display the R2 score, MSE, and mean value
print(f'R-squared (R2) Score: {r2:.2f}')
print(f'Mean Squared Error (MSE): {mse:.2f}')
print(f'Mean Value of y_test: {mean_value:.2f}')

R-squared (R2) Score: 0.99
Mean Squared Error (MSE): 0.01
Mean Value of y_test: 5.98


Logistic regression is a statistical method used for binary classification, which means it's used to predict the probability of a binary outcome (e.g., true/false, 0/1, yes/no). It's a type of regression analysis where the dependent variable is categorical. The model forms a logistic function to model the probability of the binary outcome.

On the other hand, decision tree regression is a non-parametric supervised learning method used for classification and regression. In the context of regression, it works by partitioning the data into subsets that contain similar values and then predicts the target value for the subset based on the average or majority of the observed values. It's called a "tree" because it's visually represented as a tree structure